<?php
require_once 'session_config.php'; 
require 'config.php';
require('fpdf.php');

$current_user = isset($_SESSION['valid']) ? $_SESSION['valid'] : 'Unknown User';

date_default_timezone_set('Australia/Perth');

function money($n){ return number_format((float)$n, 2); }

$start_date = isset($_POST['start_date']) && $_POST['start_date'] !== '' ? $_POST['start_date'] : date('Y-m-d', strtotime('-30 days'));
$end_date   = isset($_POST['end_date'])   && $_POST['end_date']   !== '' ? $_POST['end_date']   : date('Y-m-d');

$display_start = date('F j, Y', strtotime($start_date));
$display_end   = date('F j, Y', strtotime($end_date));

$total_revenue = 0.0;

// Fetch services joined with users
$sql = "
    SELECT s.services_id, s.services_description, s.services_price, 
           s.services_customer_cash, s.services_customer_change, 
           s.services_date, u.first_name, u.last_name
    FROM services s
    LEFT JOIN users u ON s.Id = u.Id
    WHERE DATE(s.services_date) BETWEEN '$start_date' AND '$end_date'
    ORDER BY s.services_date DESC
";
$res = $con->query($sql);

$services = [];
while($row = $res->fetch_assoc()){
    $total_revenue += (float)$row['services_price'];
    $services[] = $row;
}

class PDF extends FPDF {
    function Header(){
        $this->SetFont('Arial','B',18);
        $this->Cell(0,6,'Services Report',0,1,'C');
        $this->SetFont('Arial','B',10);
        $this->Cell(0,6,'RBM Motorparts, Accessories, & Services',0,1,'C');
        $this->Ln(3);
    }
    function Footer(){
        global $display_start, $display_end;
        $this->SetY(-28);
        $this->SetFont('Arial','I',8);
        $this->Cell(0,5,'Generated: '.date('F j, Y g:i A'),0,1,'R');
    }
}

$pdf = new PDF('P','mm','A4');
$pdf->SetAutoPageBreak(true, 28);
$pdf->AddPage();
$pdf->SetFont('Arial','',10);

// Summary
$pdf->SetFont('Arial','B',11);
$pdf->Cell(0,6,'Generated by: '.$current_user,0,1,'L');
$pdf->Cell(0,5,"Report period: $display_start to $display_end",0,1,'L');
$pdf->Ln(2);
$pdf->SetFont('Arial','',10);
$pdf->Cell(70,6,"Total Revenue from Services:",0,0);
$pdf->Cell(0,6,'PHP '.money($total_revenue),0,1);

$pdf->Ln(6);

// Table Header
$pdf->SetFont('Arial','B',8);
$pdf->Cell(25,7,'Date',1,0,'C');
$pdf->Cell(50,7,'Description',1,0,'L');
$pdf->Cell(20,7,'Price',1,0,'R');
$pdf->Cell(20,7,'Cash',1,0,'R');
$pdf->Cell(20,7,'Change',1,0,'R');
$pdf->Cell(35,7,'Handled By',1,1,'L');

// Table Rows
$pdf->SetFont('Arial','',8);
if (count($services) === 0) {
    $pdf->Cell(0,6,'No services recorded in the selected period.',1,1);
} else {
    foreach($services as $srv){
        $pdf->Cell(25,6,date('M j, Y', strtotime($srv['services_date'])),1,0,'C');
        $pdf->Cell(50,6,substr($srv['services_description'],0,30),1,0,'L');
        $pdf->Cell(20,6,money($srv['services_price']),1,0,'R');
        $pdf->Cell(20,6,money($srv['services_customer_cash']),1,0,'R');
        $pdf->Cell(20,6,money($srv['services_customer_change']),1,0,'R');       
        $pdf->Cell(35,6,$srv['first_name'].' '.$srv['last_name'],1,1,'L');
    }
}

/* ===============================
   SYSTEM LOG INSERTION SECTION
   =============================== */

// Fetch current user details from database
$user_query = $con->prepare("SELECT Id, Username, role FROM users WHERE Username = ?");
$user_query->bind_param("s", $current_user);
$user_query->execute();
$user_result = $user_query->get_result();
$user_data = $user_result->fetch_assoc();

$user_id = $user_data['Id'] ?? 0;
$username = $user_data['Username'] ?? $current_user;
$user_role = $user_data['role'] ?? 'Unknown';

// Prepare log data
$action_type = "Generate Service Report";
$description = "Generated services report from $display_start to $display_end";
$module = "Report";
$submodule = "Generate Service Report";
$result = "Success";
$log_date = date('Y-m-d');
$log_time = date('H:i:s');

// Insert into system_log table
$log_stmt = $con->prepare("
    INSERT INTO system_log 
    (user_id, username, user_role, action_type, description, module, submodule, result, date, time)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
");
$log_stmt->bind_param(
    "isssssssss",
    $user_id,
    $username,
    $user_role,
    $action_type,
    $description,
    $module,
    $submodule,
    $result,
    $log_date,
    $log_time
);
$log_stmt->execute();

/* =============================== */

$pdf->Output('I', 'services_report_'.date('Y-m-d',strtotime($start_date)).'_to_'.date('Y-m-d',strtotime($end_date)).'.pdf');
exit;
?>
