<?php
require_once 'session_config.php'; 
require 'config.php';
require('fpdf.php');

$current_user = isset($_SESSION['valid']) ? $_SESSION['valid'] : 'Unknown User';

date_default_timezone_set('Australia/Perth');

function money($n){ return number_format((float)$n, 2); }

$start_date = isset($_POST['start_date']) && $_POST['start_date'] !== '' ? $_POST['start_date'] : date('Y-m-d', strtotime('-30 days'));
$end_date   = isset($_POST['end_date'])   && $_POST['end_date']   !== '' ? $_POST['end_date']   : date('Y-m-d');

$display_start = date('F j, Y', strtotime($start_date));
$display_end   = date('F j, Y', strtotime($end_date));

$start_display = date("F j, Y", strtotime($start_date));
$end_display   = date("F j, Y", strtotime($end_date));

// --- Fetch products ---
// ✅ Added `p.cost` to the SELECT
$res = $con->query("SELECT p.product_id, p.name, p.barcode, p.category, p.model, 
                           p.quantity, p.price, p.cost, p.supplier_id, s.supplier_name
                    FROM products p
                    LEFT JOIN suppliers s ON p.supplier_id = s.supplier_id
                    ORDER BY p.name ASC");

$products = [];
while($row = $res->fetch_assoc()){
    $products[$row['product_id']] = $row;
    $products[$row['product_id']]['units_sold'] = 0;
    $products[$row['product_id']]['stock_in'] = 0;
    $products[$row['product_id']]['profit'] = 0.0;
}

// --- Fetch sales data ---
$sales_res = $con->query("SELECT od.product_id, SUM(od.quantity) as sold_qty
                          FROM order_detail od
                          JOIN orders o ON od.order_id=o.order_id
                          WHERE DATE(o.order_date) BETWEEN '$start_date' AND '$end_date'
                          GROUP BY od.product_id");
while($s = $sales_res->fetch_assoc()){
    if(isset($products[$s['product_id']])){
        $products[$s['product_id']]['units_sold'] = (int)$s['sold_qty'];
        
        // ✅ Updated markup and profit calculations to use actual cost
        $markup = $products[$s['product_id']]['price'] - $products[$s['product_id']]['cost'];
        $products[$s['product_id']]['profit'] = $markup * $s['sold_qty'];
    }
}

// --- Fetch stock in data ---
$stockin_res = $con->query("SELECT product_id, SUM(qty) as in_qty
                            FROM stock_in
                            WHERE DATE(date_time) BETWEEN '$start_date' AND '$end_date'
                            GROUP BY product_id");
while($st = $stockin_res->fetch_assoc()){
    if(isset($products[$st['product_id']])){
        $products[$st['product_id']]['stock_in'] = (int)$st['in_qty'];
    }
}

// --- Summary totals ---
$total_inventory_value = 0.0;
$total_potential_profit = 0.0;
$total_units_sold = 0;
$total_profit = 0.0;

foreach($products as $p){
    $total_inventory_value += $p['quantity'] * $p['price'];

    // ✅ Use real cost instead of 70% assumption
    $total_potential_profit += $p['units_sold'] * ($p['price'] - $p['cost']);
    $total_units_sold += $p['units_sold'];
    $total_profit += $p['profit'];
}

class PDF extends FPDF {
    function Header(){
        $this->SetFont('Arial','B',16);
        $this->Cell(0,7,'Inventory Report',0,1,'C');
        $this->SetFont('Arial','',10);
        $this->Cell(0,5,'RBM Motorparts, Accessories, & Services',0,1,'C');
        $this->Ln(4);
    }
    function Footer(){
        global $display_start, $display_end;
        $this->SetY(-20);
        $this->SetFont('Arial','I',8);
        //$this->Cell(0,5,"Report period: $display_start to $display_end",0,1,'L');
        $this->Cell(0,5,'Generated: '.date('F j, Y g:i A'),0,1,'R');
    }
}

// Helper: prints each word on its own line inside a cell
function WordCell($w, $h, $txt, $border=1, $align='C'){
    global $pdf;
    $words = explode(' ', trim($txt));
    $x = $pdf->GetX();
    $y = $pdf->GetY();
    $maxHeight = count($words) * $h;
    foreach($words as $i => $word){
        $pdf->SetXY($x, $y + ($i * $h));
        $pdf->Cell($w, $h, $word, 0, 0, $align);
    }
    $pdf->Rect($x, $y, $w, $maxHeight);
    $pdf->SetXY($x + $w, $y);
    return $maxHeight;
}

$pdf = new PDF('L','mm','A4');
$pdf->AddPage();
$pdf->SetFont('Arial','',10);

// --- Summary ---
$pdf->SetFont('Arial','B',11);
//$pdf->Cell(0,6,utf8_decode("Summary ({$start_display} - {$end_display})"),0,1);
$pdf->Cell(0,6,'Generated by: '.$current_user,0,1,'L');
$pdf->Cell(0,5,"Report period: $display_start to $display_end",0,1,'L');

$pdf->Ln(1);
$pdf->SetFont('Arial','',10);
//$pdf->Cell(60,6,"Total Inventory Value:",0,0);
//$pdf->Cell(0,6,'PHP '.money($total_inventory_value),0,1);
//$pdf->Cell(60,6,"Total Potential Profit:",0,0);
//$pdf->Cell(0,6,'PHP '.money($total_potential_profit),0,1);

$pdf->Ln(4);

// --- Table Header ---
$pdf->SetFont('Arial','B',8);
$pdf->Cell(149,6,'Inventory',1,0,'C'); 
$pdf->Cell(60,6,'Sales',1,0,'C');     
$pdf->Cell(40,6,'Delivery',1,1,'C');

$pdf->Cell(20,6,'Product Code',1,0,'C');
$pdf->Cell(40,6,'Product',1,0,'C');
$pdf->Cell(30,6,'Category',1,0,'C');
$pdf->Cell(19,6,'Model',1,0,'C');
$pdf->Cell(20,6,'Qty',1,0,'C');
$pdf->Cell(20,6,'Retail Price',1,0,'C');
$pdf->Cell(20,6,'Units Sold',1,0,'C');
$pdf->Cell(20,6,'Markup',1,0,'C');
$pdf->Cell(20,6,'Profit',1,0,'C');
$pdf->Cell(20,6,'Stock In',1,0,'C');
$pdf->Cell(20,6,'Supplier',1,1,'C');

$pdf->SetFont('Arial','',7);

// --- Table Body ---
foreach($products as $p){
    // ✅ Markup = price - cost
    $markup = $p['price'] - $p['cost'];

    $pdf->Cell(20,5,$p['product_id'],1,0,'C');
    $pdf->Cell(40,5,$p['name'],1,0,'L');
    $pdf->Cell(30,5,$p['category'],1,0,'L');
    $pdf->Cell(19,5,$p['model'],1,0,'L');
    $pdf->Cell(20,5,$p['quantity'],1,0,'C');
    $pdf->Cell(20,5,money($p['price']),1,0,'R');
    $pdf->Cell(20,5,$p['units_sold'],1,0,'C');
    $pdf->Cell(20,5,money($markup),1,0,'R');
    $pdf->Cell(20,5,money($p['profit']),1,0,'R');
    $pdf->Cell(20,5,$p['stock_in'],1,0,'C');
    $pdf->Cell(20,5,$p['supplier_name'],1,1,'L');
}

// --- Totals Row ---
$pdf->SetFont('Arial','B',8);
$pdf->Cell(20,6,'Total',1,0,'C');
$pdf->Cell(129,6,'',1,0,'C');
$pdf->Cell(20,6,$total_units_sold,1,0,'C');
$pdf->Cell(20,6,'-',1,0,'C');
$pdf->Cell(20,6,money($total_profit),1,0,'R');
$pdf->Cell(40,6,'',1,1,'C');

// --- Log action to system_log ---
if (!empty($current_user)) {
    // Get user info from the users table
    $stmt_user = $con->prepare("SELECT Id, Username, role FROM users WHERE Username = ?");
    $stmt_user->bind_param("s", $current_user);
    $stmt_user->execute();
    $result_user = $stmt_user->get_result();
    $user_data = $result_user->fetch_assoc();
    $stmt_user->close();

    if ($user_data) {
        $user_id   = $user_data['Id'];
        $username  = $user_data['Username'];
        $user_role = $user_data['role'];
    } else {
        $user_id   = 0;
        $username  = 'Unknown';
        $user_role = 'Unknown';
    }

    // Prepare log entry
    $action_type = 'Generate Inventory Report';
    $description = "Generated inventory report for period $display_start to $display_end";
    $module      = 'Report';
    $submodule   = 'Generate Inventory Report';
    $result      = 'Success';
    $date        = date('Y-m-d');
    $time        = date('H:i:s');

    $stmt_log = $con->prepare("INSERT INTO system_log 
        (user_id, username, user_role, action_type, description, module, submodule, result, date, time)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
    $stmt_log->bind_param("isssssssss", 
        $user_id, $username, $user_role, $action_type, $description, $module, $submodule, $result, $date, $time);
    $stmt_log->execute();
    $stmt_log->close();
}

$pdf->Output('I','inventory_report_'.date('Y-m-d',strtotime($start_date)).'_to_'.date('Y-m-d',strtotime($end_date)).'.pdf');
exit;
?>
